package com.example.jetpackcomposebasics.ui.theme

class Lexem {
    companion object {
        const val LoremIpsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras convallis nulla sit amet rhoncus tincidunt. Nam imperdiet libero eu eros aliquet, sit amet suscipit purus malesuada. Duis molestie, nisi eget mattis facilisis, lorem neque ornare sapien, in vulputate nibh libero ut nulla. Cras consectetur tellus vitae augue mattis, sed fermentum nulla mattis. Quisque ac nisi egestas, tempor diam vel, rhoncus elit. Pellentesque a ex eget tortor blandit efficitur vitae in ex. Curabitur at diam nec libero placerat finibus. Sed faucibus ut sem eget aliquet.\n" +
                "\n" +
                "Curabitur sodales magna vel sagittis maximus. Sed ac arcu sit amet libero lobortis ultrices at in risus. Vivamus gravida lacus mi, et pellentesque ex rutrum sit amet. Vestibulum feugiat purus id nunc facilisis dapibus. Phasellus hendrerit ante et ligula pulvinar euismod. Donec suscipit iaculis quam, non faucibus sapien consectetur porta. Integer quis volutpat diam. Donec pulvinar, odio non mattis suscipit, justo nisi convallis velit, placerat ultrices metus leo in eros. Pellentesque finibus commodo ultrices. Vestibulum sit amet augue gravida, bibendum nulla eget, semper elit. Curabitur quis libero luctus, fermentum enim non, sodales lacus. Curabitur velit massa, volutpat bibendum sapien et, varius tempus nulla. Integer consequat metus nec turpis dapibus commodo. Donec volutpat accumsan tellus et dignissim.\n" +
                "\n" +
                "Aliquam dignissim est venenatis dui consequat ultrices et id massa. Donec imperdiet sapien sit amet urna accumsan blandit. Integer dignissim nunc dui, non venenatis velit fermentum et. Mauris a hendrerit ligula. Curabitur tempus lacinia lacinia. Vivamus erat libero, laoreet eu nulla nec, viverra egestas magna. Phasellus facilisis urna sit amet consectetur ultricies. In scelerisque urna vel fermentum pharetra. Morbi felis tellus, viverra nec lectus eget, consectetur bibendum nisi. Phasellus aliquet justo quis nibh tincidunt, et iaculis erat laoreet. Proin pellentesque vestibulum sem.\n" +
                "\n" +
                "Maecenas vitae metus nec mauris laoreet euismod ut in dui. Quisque vel maximus mauris, sed posuere lectus. Aliquam lobortis elit nec mi cursus luctus. Vestibulum faucibus blandit odio, ut facilisis mi finibus et. Quisque faucibus dignissim varius. Nam quis vehicula nisi. Vestibulum vulputate condimentum sodales. Curabitur vel vestibulum enim. In maximus maximus quam, et bibendum augue finibus ac. Suspendisse non odio tincidunt, aliquet mauris mollis, scelerisque est. Phasellus in nunc pharetra, facilisis lectus a, auctor metus. Nulla nec laoreet felis.\n" +
                "\n" +
                "Quisque mi eros, sodales et gravida et, pellentesque non dolor. Donec molestie dolor ut mauris maximus, vitae porta metus commodo. In egestas elementum ipsum, eu lobortis diam dignissim vitae. In eleifend tortor vel tristique auctor. Suspendisse sed est non ante cursus euismod. Proin eleifend ultrices nulla ut elementum. Aliquam eget mi neque. Aenean fermentum, nulla id efficitur volutpat, ipsum lectus fringilla leo, id consequat ipsum nunc faucibus orci. Phasellus tincidunt est eu orci rutrum, sit amet maximus mi sagittis. Vestibulum quis ligula risus. Suspendisse vel egestas ex, sed mattis metus. Nulla eros metus, tristique a enim pellentesque, aliquam laoreet tellus."
    }
}